### ISSUE TITLE
Support for mpeg & flv

### ISSUE THREAD

**Issue by wesly-zz** [wwidd/wwidd#6]
I have a lot of MPG & FLV videos and I was wondering whether support for these formats would be considered.

**Comment by danstocker** [comment]
I'm gonna check whether both FFmpeg and VLC support them. Unless they don't, adding support to Wwidd should be very simple.

**Comment by wesly-zz** [comment]
I've been using VLC player to playback these files so VLC definitely supports these formats (which format doesn't VLC support ?:)

**Comment by gwhiteside** [comment]
Seeing as how this issue is about a year old, I wanted to leave a comment to anyone who doesn't mind tweaking their local copy a little. As danstocker indicated, this is a pretty trivial change, thanks to his design. Look at server/src/utils/walker.js line 20:

``` javascript
options = options || { filter: new RegExp('^.+\\.(wmv|avi|mov|mp4|mkv)$', 'ig'), hidden: false };
```

Simply add your desired extension(s) to the regular expression, e.g. to add .mpg and .flv files:

``` javascript
options = options || { filter: new RegExp('^.+\\.(wmv|avi|mov|mp4|mkv|mpg|flv)$', 'ig'), hidden: false };
```

As wesly noted, VLC supports pretty much everything under the sun. And more importantly, I (and many others) can assure that FFmpeg is quite an awesome beast, to say the least.
